### ISSUE TITLE
RGBW - Cannot control white

### ISSUE THREAD

**Issue by Dilergore** [thomasloven/lovelace-slider-entity-row#258]
My Home Assistant version: 2022.8.7

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Trying to use the `white` attribute, due to the `white_value` is deprecated.

What I expected to happen: `white` value works properly

What happened instead:
```
Uncaught TypeError: t.rgbw_color is not iterable
    at get _rgbww [as _rgbww] (slider-entity-row.js:7:842)
    at set _value [as _value] (slider-entity-row.js:7:2767)
    at set value [as value] (slider-entity-row.js:1:16749)
    at dt.<anonymous> (slider-entity-row.js:21:37)
    at W.handleEvent (slider-entity-row.js:1:14167)
    at l.fire (typography.js:181:1)
    at l.<anonymous> (paper-slider.js:314:1)
    at MutationObserver.<anonymous> (typography.js:181:1)
```

**Minimal** steps to reproduce:
Setup an MQTT RGBW light using the default schema and use the slider where the attribute config is `white`.

```yaml
type: custom:slider-entity-row
entity: light.ledstrip
icon: mdi:led-strip
name: "Led Strip"
toggle: true
min: 1
step: 1
hide_when_off: true
attribute: white
```

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Dilergore** [comment]
My bad, I realized I had an issue with the MQTT Light itself.
